var array=["It's so crazy right now!",
"Most incredibly, it's ya girl, Bee,",
'You ready?',
'Uh oh, uh oh, uh oh, oh no no', 
"When you leave I'm begging you not to go",
"How I'm feeling and my pride is the one to blame",
'Such a funny thing for me to try to explain',
'Better yet a hood look',
'Thats a good look',
'Switch your neck ties to purple labels',
'Lemme upgrade you',
'Mission four: Got the vintage Rolls Drop a couple hundreds tell him leave it at the door',
'Mission three: Got my three best friends Like we do it all the time we gonna do it again (hey)',
"Mission two: Gotta make that call, Tell him get the bottles poppin' when they play my song (hey)",
"Mission one: I'ma put this on When he see me in the dress I'ma get me some (hey)",
"I ain't worried doing me tonight",
"To the left, to the left",
"Everything you own in the box to the left",
"You must not know about me, you must not know about me",
"Baby drop them keys",
"If I were a boy",
"I think I could understand how it feels to love a girl I swear I’d be a better man.",
"I’d listen to her 'Cause I know how it hurts",
"When you lose the one you wanted 'Cause he’s taken you for granted And everything you had got destroyed",
"All the single ladies (All the single ladies)",
"All the single ladies",
"Now put your hands up",
"Cause if you liked it then you should have put a ring on it",
"See me up in the club with 50-leven girls",
"Posted in the back diamond fangs in my grill",
"Brooklyn brim with my eyes sittin' low",
"And every girl in here gotta look me up and down",
"All on Instagram, cake by the pound",
"Circulate the image every time I come around",
"G's up, tell me how I'm lookin' babe",
"Drop the bass, man, the bass get lower",
"radio say, Speed it up, I just go slower",
"The man ain't ever seen a booty like this",
"And why you think you keep my name rollin' off the tongue?",
"Cause when you wanna smash, I just write another one",
"I sneezed on the beat and the beat got sicker",
"I sneezed on the beat and the beat got sicker",
"I sneezed on the beat and the beat got sicker"
];
module.exports = array;  



